# ColoradarPlus Processing Configuration

main_bag_directory_path: "/root/bags/WITH_GT"
main_kitti_directory_path: "/root/coloradar_plus/kitti"
generate_sequence_run_stats: true
display_rosbag_data: false

sequences:
  bike_path:
    runs: [0, 1, 2, 3]