# ColoradarPlus Processing Configuration

main_bag_directory_path: "/root/bags"
main_kitti_directory_path: "/root/bags/bin_dataset/kitti"
generate_sequence_run_stats: true
display_rosbag_data: false

sequences:
  bike_path:
    runs: [0_liosam, 1_liosam, 2_liosam, 3_liosam]