# ColoradarPlus Processing Configuration

main_bag_directory_path: "/root/coloradar_plus"
main_kitti_directory_path: "/root/coloradar_plus/bin_dataset/kitti"
generate_sequence_run_stats: true
display_rosbag_data: false

sequences:
  bike_path:
    runs: [2_liosam]